"""Core domain models and runtime services for CamLabel3D."""

from .bev import (
    DEFAULT_TRAJECTORY_WINDOW_FRAMES,
    BEVArrow,
    BEVBox,
    BEVCurrentPose,
    BEVScene,
    BEVTrajectorySample,
    BEVViewport,
    build_bev_scene,
    derive_bev_overview_path,
    render_bev_overview,
    select_default_bev_frame_index,
    select_default_bev_track_id,
)
from .detector import DetectorAdapter
from .frame_provider import (
    FrameProvider,
    ImageFolderFrameProvider,
    VideoFrameProvider,
    open_media_source,
)
from .models import (
    DetectionConfig,
    DetectionRecord,
    PointPrompt,
    PromptMode,
    PromptSpec,
    SourceContext,
    SourceMode,
)
from .postprocess import FilterConfig, PostprocessSession, TrackSummary, WorkflowStage, clone_records
from .processing import (
    TRACK_BATCH_NUMERIC_FIELDS,
    BulkOperation,
    BulkOperationRegistry,
    OperationResult,
    OperationScope,
    OutlierHit,
    OutlierRule,
    OutlierRuleRegistry,
    OutlierScope,
    ParameterSpec,
    ProcessingContext,
    ProcessingEngine,
    ProcessingScope,
    TrackBatchEditRequest,
    TrackBatchOperationKind,
    apply_track_batch_edit,
    build_default_bulk_operation_registry,
    build_default_outlier_registry,
    hits_to_report_json,
    track_batch_records,
)
from .source_config import DatasetConfigStore, DatasetSourceConfig, DatasetSourcesConfig, IntrinsicsPreset
from .tracking import TrackingConfig, TrackingEngine

__all__ = [
    "BEVArrow",
    "BEVBox",
    "BEVCurrentPose",
    "BEVScene",
    "BEVTrajectorySample",
    "BEVViewport",
    "DatasetConfigStore",
    "DatasetSourceConfig",
    "DatasetSourcesConfig",
    "DEFAULT_TRAJECTORY_WINDOW_FRAMES",
    "DetectionConfig",
    "DetectionRecord",
    "DetectorAdapter",
    "BulkOperation",
    "BulkOperationRegistry",
    "FrameProvider",
    "FilterConfig",
    "ImageFolderFrameProvider",
    "IntrinsicsPreset",
    "OperationResult",
    "OperationScope",
    "OutlierHit",
    "OutlierRule",
    "OutlierRuleRegistry",
    "OutlierScope",
    "ParameterSpec",
    "PointPrompt",
    "PostprocessSession",
    "ProcessingContext",
    "ProcessingEngine",
    "ProcessingScope",
    "PromptMode",
    "PromptSpec",
    "SourceContext",
    "SourceMode",
    "TRACK_BATCH_NUMERIC_FIELDS",
    "TrackSummary",
    "TrackBatchEditRequest",
    "TrackBatchOperationKind",
    "TrackingConfig",
    "TrackingEngine",
    "VideoFrameProvider",
    "WorkflowStage",
    "apply_track_batch_edit",
    "build_bev_scene",
    "build_default_bulk_operation_registry",
    "build_default_outlier_registry",
    "clone_records",
    "derive_bev_overview_path",
    "hits_to_report_json",
    "open_media_source",
    "render_bev_overview",
    "select_default_bev_frame_index",
    "select_default_bev_track_id",
    "track_batch_records",
]
